bt_vendor_qcom: Resolve missing O_CREAT mode
hardware/qcom/bt-caf/libbt-vendor/src/bt_vendor_qcom.c:489:65:
error: 'open' has superfluous mode bits; missing O_CREAT?

Signed-off-by: Adithya R <adithya.r02@outlook.com>